name: GH-deploy

on:
  push:
    branches:
      - master
jobs:
  build-and-deploy:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1

    - name: Build
      run: |
        npm i
        npm run build

    - name: Deploy
      uses: JamesIves/github-pages-deploy-action@releases/v3
      with:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        BRANCH: gh-pages
        FOLDER: dist

    # DEPLOY HACK (we push empty commit to trigger GH Pages build)
    - name: Commit files (to deploy empty commit)
      run: |
        git stash
        git fetch
        git checkout gh-pages
        git pull
        git config --local user.email "Suvorovalex1997@gmail.com"
        git config --local user.name "hatskier"
        git commit -m 'rebuild pages' --allow-empty
    - name: Push changes (to deploy empty commit)
      uses: ad-m/github-push-action@master
      with:
        branch: gh-pages
        github_token: ${{ secrets.GITHUB_TOKEN }}
